# Generated by Django 3.2.3 on 2021-05-17 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(default='ea43533@gmail.com', max_length=254),
            preserve_default=False,
        ),
    ]
